
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manoj Aberathna
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        studentdetailss = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stid = new javax.swing.JTextField();
        stname = new javax.swing.JTextField();
        staddress = new javax.swing.JTextField();
        stgender = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        stknowledge = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        stsubject = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bkquantity = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bkid = new javax.swing.JTextField();
        bkname = new javax.swing.JTextField();
        bkauthor = new javax.swing.JTextField();
        lblquantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        stdt = new com.toedter.calendar.JDateChooser();
        isuebtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        studentdetailss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentdetailss.setText("Student_Details");

        jLabel7.setText("Student_Name");

        jLabel8.setText("Gender");

        jLabel9.setText("Address");

        jLabel10.setText("Student_ID");

        jLabel11.setText("Knowledge");

        jLabel12.setText("Subject");

        stsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stsubjectActionPerformed(evt);
            }
        });

        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(studentdetailss, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stname, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(stid)
                            .addComponent(staddress)
                            .addComponent(stgender)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stknowledge)
                            .addComponent(stsubject))))
                .addGap(106, 106, 106))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentdetailss)
                    .addComponent(jButton2))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(staddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(stid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(stname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stknowledge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 25, -1, -1));

        bkquantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Book_Details");

        jLabel3.setText("Book_Name");

        jLabel5.setText("Quantity");

        jLabel4.setText("Author");

        jLabel2.setText("Book_ID");

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bkquantityLayout = new javax.swing.GroupLayout(bkquantity);
        bkquantity.setLayout(bkquantityLayout);
        bkquantityLayout.setHorizontalGroup(
            bkquantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkquantityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bkquantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkquantityLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(bkquantityLayout.createSequentialGroup()
                        .addGroup(bkquantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(bkquantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bkid, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(bkname)
                            .addComponent(bkauthor)
                            .addComponent(lblquantity))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bkquantityLayout.setVerticalGroup(
            bkquantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkquantityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bkquantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bkquantityLayout.createSequentialGroup()
                        .addComponent(bkname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(bkauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(bkquantityLayout.createSequentialGroup()
                        .addGroup(bkquantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(67, 67, 67)
                        .addGroup(bkquantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(bkid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addGroup(bkquantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bkquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bkquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 25, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Issu_ Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 110, -1));
        getContentPane().add(stdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 213, -1));

        isuebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-issue-32.png"))); // NOI18N
        isuebtn.setText("Issue");
        isuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isuebtnActionPerformed(evt);
            }
        });
        getContentPane().add(isuebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 530, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-back-32.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 530, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/R (2).jpeg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 630));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/R (2).jpeg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, -110, 980, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String sql = "SELECT * FROM users WHERE sno = ?";
    try {
        // Establish connection to the database
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb", "root", "");
        
        // Create a prepared statement to execute the query
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, stid.getText());
        
        // Execute the query
        ResultSet rs = pst.executeQuery();
        
        // Check if a record was found
        if (rs.next()) {
            // Set text fields with data from the result set
            stid.setText(rs.getString("sno"));
            stname.setText(rs.getString("name"));
            staddress.setText(rs.getString("address"));
            stgender.setText(rs.getString("gender"));
             stknowledge.setText(rs.getString("knowledge"));
             stsubject.setText(rs.getString("subject"));
            
            JOptionPane.showMessageDialog(null, "student details retrieved successfully");
        } else {
            JOptionPane.showMessageDialog(null, "No student found with the given ID");
        }
        
        // Close the result set and statement
        rs.close();
        pst.close();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM book WHERE bookID = ?";
        try {
            // Establish connection to the database
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb", "root", "");

            // Create a prepared statement to execute the query
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, bkid.getText());

            // Execute the query
            ResultSet rs = pst.executeQuery();

            // Check if a record was found
            if (rs.next()) {
                // Set text fields with data from the result set
                bkid.setText(rs.getString("bookID"));
                bkname.setText(rs.getString("name"));
                bkauthor.setText(rs.getString("author"));
                lblquantity.setText(rs.getString("quantity"));

                JOptionPane.showMessageDialog(null, "Book details retrieved successfully");
            } else {
                JOptionPane.showMessageDialog(null, "No book found with the given ID");
            }

            // Close the result set and statement
            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void stsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stsubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stsubjectActionPerformed

    private void isuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isuebtnActionPerformed
        // TODO add your handling code here:
 
        String getQuantitySql = "SELECT quantity FROM book WHERE bookID = ?";
    String updateQuantitySql = "UPDATE book SET quantity = ? WHERE bookID = ?";
    String issueBookSql = "INSERT INTO issue(bookID, bookname, author, quantity, sid, sname, address, gender, knowledge, subject, issudate) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try {
        // Establish database connection
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb", "root", "");

        // Prepare statement to get the current quantity
        PreparedStatement getQuantityPst = con.prepareStatement(getQuantitySql);
        getQuantityPst.setString(1, bkid.getText());
        ResultSet rs = getQuantityPst.executeQuery();

        int currentQuantity = 0;
        if (rs.next()) {
            currentQuantity = rs.getInt("quantity");
        } else {
            JOptionPane.showMessageDialog(null, "Book ID not found.");
            return;
        }

        // Check if the book is available
        if (currentQuantity <= 0) {
            JOptionPane.showMessageDialog(null, "No copies of the book are available for issue.");
            return;
        }

        // Decrement the quantity
        int newQuantity = currentQuantity - 1;

        // Prepare statement to update the new quantity
        PreparedStatement updateQuantityPst = con.prepareStatement(updateQuantitySql);
        updateQuantityPst.setInt(1, newQuantity);
        updateQuantityPst.setString(2, bkid.getText());
        updateQuantityPst.executeUpdate();

        // Prepare statement to issue the book
        PreparedStatement issueBookPst = con.prepareStatement(issueBookSql);
        issueBookPst.setString(1, bkid.getText());
        issueBookPst.setString(2, bkname.getText());
        issueBookPst.setString(3, bkauthor.getText());
        issueBookPst.setString(4, String.valueOf(newQuantity));  // Updated quantity after issue
        issueBookPst.setString(5, stid.getText());
        issueBookPst.setString(6, stname.getText());
        issueBookPst.setString(7, staddress.getText());
        issueBookPst.setString(8, stgender.getText());
        issueBookPst.setString(9, stknowledge.getText());
        issueBookPst.setString(10, stsubject.getText());

        // Extract the date from JDateChooser and format it
        Date date = stdt.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = sdf.format(date);
        issueBookPst.setString(11, formattedDate);

        // Execute the issue book statement
        issueBookPst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Book issued successfully");

        // Close all statements and connection
        issueBookPst.close();
        updateQuantityPst.close();
        getQuantityPst.close();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
        
        
    }//GEN-LAST:event_isuebtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           this.toBack();
        setVisible(false);
        new MainMenu().toFront();
        new MainMenu().setState(java.awt.Frame.NORMAL);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bkauthor;
    private javax.swing.JTextField bkid;
    private javax.swing.JTextField bkname;
    private javax.swing.JPanel bkquantity;
    private javax.swing.JButton isuebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lblquantity;
    private javax.swing.JTextField staddress;
    private com.toedter.calendar.JDateChooser stdt;
    private javax.swing.JTextField stgender;
    private javax.swing.JTextField stid;
    private javax.swing.JTextField stknowledge;
    private javax.swing.JTextField stname;
    private javax.swing.JTextField stsubject;
    private javax.swing.JLabel studentdetailss;
    // End of variables declaration//GEN-END:variables
}
