
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.security.auth.Subject;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manoj Aberathna
 */
public class NewStudent extends javax.swing.JFrame {

    /**
     * Creates new form NewStudent
     */
    String gender;
    public NewStudent() {
        initComponents();
        show_user();
    }
    public ArrayList<User>userList(){
        ArrayList<User> usersList = new ArrayList<>();
        
    try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb", "root", "");
            String Query1="select * from users";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(Query1);
            User user;
            while(rs.next()){
                user=new User(rs.getInt("sno"), rs.getString("name"), rs.getString("address"),  rs.getString("gender"),  rs.getString("knowledge"),  rs.getString("subject"));
                usersList.add(user);
                
                
                    
            }
            
            
            
           }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
        return usersList;
        
    }
    public void show_user(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable1_Display_User.getModel();
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getsno();
            row[1] = list.get(i).getname();
            row[2] = list.get(i).getaddress();
            row[3] = list.get(i).getgender();
            row[4] = list.get(i).knowledge();
            row[5] = list.get(i).getsubject();
            model.addRow(row);
        }
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        subject = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        sno = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        python = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        coreJava = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Display_User = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 2), "New Student Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Std_No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 46, -1, -1));

        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-reset-32 (1).png"))); // NOI18N
        resetBtn.setText("reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, 40));

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Degree Information Technology", "Diploma in  Information Technology" }));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 244, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Knowledge");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        buttonGroup3.add(female);
        female.setText("female");
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Subject");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 246, -1, -1));

        buttonGroup3.add(male);
        male.setText("male");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 159, -1, -1));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 119, 210, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 86, -1, -1));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-32 (1).png"))); // NOI18N
        saveBtn.setText("save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 110, 40));
        jPanel1.add(sno, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 44, 210, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 84, 210, -1));

        python.setText("python");
        jPanel1.add(python, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 121, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        coreJava.setText("java");
        jPanel1.add(coreJava, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 202, -1, -1));

        jTable1_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Std_No", "Name", "Address", "Gender", "Knowledge", "Subject"
            }
        ));
        jTable1_Display_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_Display_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_Display_User);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, 230));

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-32 (1).png"))); // NOI18N
        updateBtn.setText("update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, 40));

        deleteBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manoj Aberathna\\Downloads\\icons8-delete-32.png")); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-back-32.png"))); // NOI18N
        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 950, 380));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/R (2).jpeg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -20, -1, 670));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/R (2).jpeg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -150, 950, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb", "root", "");
            String Query = "insert into users(sno, name, address, gender, knowledge, subject) values(?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(Query) ;
            pst.setString(1, sno.getText());
            pst.setString(2, name.getText());
            pst.setString(3, address.getText());

            if(male.isSelected()) {
                gender="male";

            }

            if(female.isSelected()) {
                gender="female";

            }
            pst.setString(4, gender);
            String knowledge= "";
            if(coreJava.isSelected()){
                knowledge+=coreJava.getText()+" ";
            }
            if(python.isSelected()){
                knowledge+=python.getText()+" ";
            }
            pst.setString(5,knowledge);
            String course;
            course=subject.getSelectedItem().toString();
            pst.setString(6,course);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable1_Display_User.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "insert successfull ");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        sno.setText("");
        name.setText("");
        address.setText("");
        buttonGroup3.clearSelection();
        subject.setSelectedIndex(0);
        coreJava.setSelected(false);
        python.setSelected(false);

    }//GEN-LAST:event_resetBtnActionPerformed

    private void jTable1_Display_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_Display_UserMouseClicked
        // TODO add your handling code here:
        int i = jTable1_Display_User.getSelectedRow();        
        TableModel model = jTable1_Display_User.getModel();
        sno.setText(model.getValueAt(i,0).toString());
        name.setText(model.getValueAt(i,1).toString());
        address.setText(model.getValueAt(i,2).toString());
        String sex = model.getValueAt(i,3).toString();
        if(sex.equals("model")){
            male.setSelected(true);
            
          }
        else{
            female.setSelected(true);
        }
        String knowledge = model.getValueAt(i,4).toString();
        switch (knowledge) {
    case "java":
        coreJava.setSelected(true);
        python.setSelected(false);
        break;
      case "python":
        python.setSelected(true);
        coreJava.setSelected(false);
        break;
      default:      
          
        coreJava.setSelected(true);
        python.setSelected(true);
        break;
        }
     String subject1 = model.getValueAt(i,5).toString();   
       switch (subject1) {
       case "Computer Science":
       subject.setSelectedIndex(0);
        break;
         case "Degree Information Technology":
       subject.setSelectedIndex(0);
        break;        
       case "Deploma in Information Technology":
       subject.setSelectedIndex(0);
        break;  
        }
        
        
        
        
    }//GEN-LAST:event_jTable1_Display_UserMouseClicked

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb", "root", "");
            int row = jTable1_Display_User.getSelectedRow();
            String value = (jTable1_Display_User.getModel().getValueAt(row, 0).toString());
            String Query = "update users set sno=?, name=?, address=?, gender=?, knowledge=?, subject=? where sno="+value;
             PreparedStatement pst = con.prepareStatement(Query) ;
            pst.setString(1, sno.getText());
            pst.setString(2, name.getText());
            pst.setString(3, address.getText());
            if(male.isSelected()) {
                gender="male";

            }

            if(female.isSelected()) {
                gender="female";

            }
            pst.setString(4, gender);
            String knowledge= "";
            if(coreJava.isSelected()){
                knowledge+=coreJava.getText()+" ";
            }
            if(python.isSelected()){
                knowledge+=python.getText()+" ";
            }
            pst.setString(5,knowledge);
            String course;
            course=subject.getSelectedItem().toString();
            pst.setString(6,course);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable1_Display_User.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Updated successfull ");

            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb", "root", "");
             int row = jTable1_Display_User.getSelectedRow();
            String value = (jTable1_Display_User.getModel().getValueAt(row, 0).toString());
            String Query = "delete from users where sno="+value;
            PreparedStatement pst = con.prepareStatement(Query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable1_Display_User.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Deleted Succesfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
        
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new MainMenu().toFront();
        new MainMenu().setState(java.awt.Frame.NORMAL);
        
        
        
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox coreJava;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_Display_User;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JCheckBox python;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField sno;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
